
##############################################################################
#
# Builder Module Manifest.
#
# Autogenerated 2015-05-12 03:09:55.530807
#
##############################################################################
BASEDIR := $(dir $(lastword $(MAKEFILE_LIST)))
indigo_ofdpa_driver_BASEDIR := $(BASEDIR)indigo_ofdpa_driver
ofdpa_tools_BASEDIR := $(BASEDIR)ofdpa_tools


ALL_MODULES := $(ALL_MODULES) indigo_ofdpa_driver ofdpa_tools
