###############################################################################
#
# 
#
###############################################################################
include ../../init.mk
MODULE := indigo_ofdpa_driver
AUTOMODULE := indigo_ofdpa_driver
include $(BUILDER)/definemodule.mk
