
###############################################################################
#
# Inclusive Makefile for the ofdpa_l2play module.
#
# Autogenerated 2015-08-16 14:36:27.573562
#
###############################################################################
ofdpa_l2play_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(ofdpa_l2play_BASEDIR)/module/make.mk
include $(ofdpa_l2play_BASEDIR)/module/auto/make.mk
include $(ofdpa_l2play_BASEDIR)/module/src/make.mk
include $(ofdpa_l2play_BASEDIR)/utest/_make.mk

